### ISSUE TITLE
 参数问题

### ISSUE THREAD

**Issue by guanleiming** [mayabot/fastText4j#10]
![default](https://user-images.githubusercontent.com/45931460/50147280-b1ce3a80-02f0-11e9-9154-30c3ca48d92a.png)
这里出现了概率大于1是什么情况？

**Comment by jimium** [comment]
这是精度问题，正常使用

guanleiming <notifications@github.com>于2018年12月18日 周二18:15写道：

**Comment by guanleiming** [comment]
![default](https://user-images.githubusercontent.com/45931460/50583753-19b28280-0ea6-11e9-9f17-ba9af5723fff.png)
你好，因为lateinit修饰wordVector会导致FastText对象序列化失败，采用fastjson的Json.toJsonString，为什么要使用这个修饰符？或者有其他的使用的序列化方法吗？我好放在缓存里面使用，谢谢
