### ISSUE TITLE
fasttext的序列化

### ISSUE THREAD

**Issue by guanleiming** [mayabot/fastText4j#11]
你好，因为lateinit修饰wordVector会导致FastText对象序列化失败，采用fastjson的Json.toJsonString，为什么要使用这个修饰符？或者有其他的使用的序列化方法吗？我好放在缓存里面使用，谢谢

**Comment by guanleiming** [comment]
![default](https://user-images.githubusercontent.com/45931460/50584448-96dff680-0eaa-11e9-9a35-250b60e58f04.png)
反序列化也有问题，FastText类没有构造函数呀

**Comment by jimium** [comment]
贴上代码吧
你是把Fasttext对象整个序列化？

**Comment by guanleiming** [comment]
![default](https://user-images.githubusercontent.com/45931460/50957396-18fa9b80-14f9-11e9-82b0-0ec21183cd2d.png)
就是这些了，会报错，没办法序列化

**Comment by jimium** [comment]
fastText对象有保存到磁盘的模型文件的方法，不要使用序列化
