### ISSUE TITLE
训练词向量时,请问如何调整bucket参数，谢谢！

### ISSUE THREAD

**Issue by alei76** [mayabot/fastText4j#12]
训练词向量时, bucket默认 [2000000],导致训练出来的模块文件太大,请问如何调整bucket参数，谢谢！

**Comment by jimium** [comment]
的确，我在参数里面没有暴露这个参数，你稍等一下

**Comment by jimium** [comment]
V1.2.3已经发布了修改，maven仓库已经同步，你可以更新新的版本试试。
增加TranArgs的配置项，可以配置bucket等参数。

new TrainArgs().setBucket(10000);

**Comment by alei76** [comment]
多谢!
