### ISSUE TITLE
您能提供全java代码吗？Kotlin不熟，还需要时间学习，如果java就直接上手撸了，程序员都喜欢这样。。。:) 

### ISSUE THREAD

**Issue by johnny0213** [mayabot/fastText4j#17]

**Comment by jimium** [comment]
我学kotlin花了2天时间， 转换还是挺快的。
fastText是从C++代码移植过来的，java的语法已经不能满足对应的表达内容！
该用JAVA的话代码量要多1到2倍。
PS：java繁琐的语法，让我比较烦躁 :)
