### ISSUE TITLE
cutoff and retrain args missing while quantizing

### ISSUE THREAD

**Issue by FireBrother** [mayabot/fastText4j#18]
您好，

我在使用中发现，quantize过程中只有dsub和qnorm两个参数发挥了作用，而cutoff和retrain并没有出现在代码中，请问是尚未完成的功能吗？如果是，近期有加入它们的计划吗？

另外，首页文档的installation中的版本号依然是1.2.2，是个没有加入minn和maxn等参数的版本，而最新版已经更新至1.2.3，这是我查看issue才发现的，请及时更新文档。

祝好

**Comment by jimium** [comment]
FireBrother 你好：
感谢你的issue

1. quantize是已经完成的功能，暂时没有关于cutoff和retrain的计划。
2. 新的计划是同步官方的0.2版本，增强对多分类的优化
3. 新版本已经开始，但是没有时间计划，因为下半年公司很忙，尽量
4. 如果quantize您可以研究一下提交Pull那就太好了

**Comment by FireBrother** [comment]
好的，谢谢回复
