### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by baiziyuandyufei** [mayabot/fastText4j#3]
When I Run `gradle compile 'com.mayabot:fastText4j:1.1.5'`,
then 
FAILURE: Build failed with an exception.

* Where:
Build file '...fastText4j/build.gradle' line: 105

* What went wrong:
A problem occurred evaluating root project 'fastText4j'.
> Could not get unknown property 'oss_user' for repository container of type org.gradle.api.internal.artifacts.dsl.DefaultRepositoryHandler.

**Comment by jimium** [comment]
fix it  v1.2.0.
