### ISSUE TITLE
刚用就OOM

### ISSUE THREAD

**Issue by lgnlgn** [mayabot/fastText4j#7]
JDK8_121   
Read file build dictionary ...

Read 0M words
Number of words:  251
Number of labels: 0
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space

只有几十行的中文 分好词 空格隔开， 测试一下训练词向量瞬间OOM   
用其他w2v java是好的，有些行比较少的词

但是做supervise没报错：
Read file build dictionary ...

Read 0M words
Number of words:  958
Number of labels: 0

Progress: 100.95% words/sec/thread: Infinity lr: -0.00095 loss: 0.00000 ETA: 0h 0m 0s
Progress: 100.00% words/sec/thread: Infinity lr: 0.00000 loss: 0.00000 ETA: 0h 0m 0s
Train use time 123 ms

**Comment by jimium** [comment]
你能把测试“几十行的中文 分好词 空格隔开”这个例子贴给我？

**Comment by lgnlgn** [comment]
2018-12-17 

gnliang10 



发件人：jimi <notifications@github.com>
发送时间：2018-12-16 14:26
主题：Re: [mayabot/fastText4j] 刚用就OOM (#7)
收件人："mayabot/fastText4j"<fastText4j@noreply.github.com>
抄送："Guoning Liang"<gnliang10@126.com>,"Author"<author@noreply.github.com>

你能把测试“几十行的中文 分好词 空格隔开”这个例子贴给我？
